# Generated by Django 5.1.3 on 2024-12-22 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
        ('utilisateurs', '0004_alter_mecanicien_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='mecanicien',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='utilisateurs.mecanicien'),
        ),
    ]
