# Generated by Django 5.1.3 on 2024-12-25 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_facture_client_alter_facture_mecanicien'),
        ('rendez_vous', '0002_rendezvous_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='rendezvous',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='rendez_vous.rendezvous'),
        ),
    ]
