# Generated by Django 5.1.3 on 2024-12-18 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('service', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_client', to='utilisateurs.client')),
                ('mecanicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_mecanicien', to='utilisateurs.mecanicien')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_vehicule', to='vehicules.vehicule')),
            ],
        ),
    ]
