# Generated by Django 5.1.3 on 2024-12-23 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_alter_mecanicien_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mecanicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='utilisateurs.mecanicien'),
        ),
    ]
